import assert from "node:assert/strict";
import { readFile, stat } from "node:fs/promises";

const source = await readFile(new URL("../dist/app.js", import.meta.url), "utf8");
const bundle = await readFile(new URL("../dist/game.bundle.js", import.meta.url), "utf8");
const html = await readFile(new URL("../dist/index.html", import.meta.url), "utf8");

const baseLevels = source.match(/const levels = \[([\s\S]*?)\.\.\.buildExpansionLevels\(\)/)?.[1];
assert.ok(baseLevels, "base level list and expansion call are present");
const baseLevelCount = [...baseLevels.matchAll(/\{ name:/g)].length;
const chapterBlock = source.match(/const expansionChapters = \[([\s\S]*?)\n\];/)?.[1];
assert.ok(chapterBlock, "expansion chapter list is present");
const chapterEntries = [...chapterBlock.matchAll(/\{ title: "([^"]+)", names: \[([^\]]+)\] \}/g)];
const chapters = chapterEntries.map(([, title, names]) => ({ title, levels: [...names.matchAll(/"([^"]+)"/g)].map(([, name]) => name) }));
assert.equal(baseLevelCount, 12, "the original twelve levels are preserved");
assert.equal(chapters.length, 9, "nine campaign chapters are present");
assert.ok(chapters.slice(0, -1).every(chapter => chapter.levels.length === 10), "the first eight chapters contain ten named levels");
assert.deepEqual(chapters.slice(-1)[0].levels.length, 8, "the final chapter contains the eight levels needed to reach 100");
assert.equal(baseLevelCount + chapters.reduce((sum, chapter) => sum + chapter.levels.length, 0), 100, "the campaign contains 100 levels total");

const boardBlock = source.match(/const expansionBoards = \[([\s\S]*?)\n\];/)?.[1] ?? "";
assert.ok(boardBlock, "hand-authored expansion board recipes are present");
const authoredBoardCount = [...boardBlock.matchAll(/\b(?:boxBoard|targetBoard|wallBoard|strokeCupBoard|groundBoard|routeBoard|spinBoard)\(/g)].length;
assert.equal(authoredBoardCount, 50, "the first 50 expansion levels have explicit authored board recipes");
const lateBlock = source.match(/const lateExpansionBoards = \[([\s\S]*?)\n\];/)?.[1] ?? "";
const lateChapterSizes = [...lateBlock.matchAll(/Array\.from\(\{ length: (\d+) \}/g)].map(([, size]) => Number(size));
assert.deepEqual(lateChapterSizes, [10, 10, 10, 8], "the late campaign adds 38 boards in four chapters");
const layoutBlock = source.match(/const lateLayouts = \[([\s\S]*?)\n\];/)?.[1] ?? "";
assert.equal([...layoutBlock.matchAll(/\{ start:/g)].length, 10, "late levels use ten authored mechanical seed layouts");
const routePlanBlock = source.match(/const lateRoutePlans = \[([\s\S]*?)\n\];/)?.[1] ?? "";
assert.equal([...routePlanBlock.matchAll(/routePlan\(/g)].length, 38, "every late level has a separately authored route skeleton");
assert.match(source, /lateRoutePlans\[chapter - 5\]\[slot\]/, "late boards receive their own route plan");
assert.match(source, /const layoutIndex = \(slot \* 3 \+ \(chapter - 5\) \* 2\) % lateLayouts\.length/, "mechanical seed layouts are reordered between chapters");
assert.match(source, /expansionBoards\.push\(\.\.\.lateExpansionBoards\)/, "late board recipes are included in the campaign");
const goalTypes = new Set([...source.matchAll(/type: "(ballBox|target|wall|strokeBox|spinGear|ground|checkpoints)"/g)].map(([, type]) => type));
assert.equal(goalTypes.size, 7, "the game supports seven distinct goal types");
assert.match(source, /checkpointHits\.size === goal\.targets\.length/, "sequential route goals complete only after all checkpoints");
assert.match(source, /goal\.type === "ground"/, "marked ground landing goals are evaluated");
assert.match(source, /const dynamicBodies = \[\]/, "pre-placed dynamic bodies are supported");
assert.match(source, /activeBodies\.forEach\(body => \{[\s\S]*?updateStrokeBody\(body, dt\)/, "pre-placed bodies receive gravity and collision updates");
assert.match(source, /\(level\.dynamics \?\? \[\]\)\.forEach\(addDynamicBar\)/, "late boards include moving support objects");
assert.match(source, /const magnets = \[\]/, "magnetic field objects are supported");
assert.match(source, /if \(chapter === 8\) magnets\.push\(mirrorMagnet\(finaleMagnetLayouts\[slot\], direction\)\)/, "the final chapter introduces a three-field magnetic puzzle");
assert.match(source, /applyMagneticForce\(ball\.position, ballVelocity/, "magnetic fields affect the ball");
assert.match(source, /applyMagneticForceToBody\(body, dt\)/, "magnetic fields apply torque to drawn bodies");
assert.match(source, /\(level\.magnets \?\? \[\]\)\.forEach\(addMagnet\)/, "late boards include magnetic field objects");
assert.match(source, /collideMovingBodies\(activeBodies\)/, "drawn objects collide with each other");
assert.match(source, /const COLLISION_CELL_SIZE = 0\.75/, "body collision broadphase uses spatial buckets");
assert.match(source, /for \(let iteration = 0; iteration < 4; iteration\+\+\)/, "static body collision resolves multiple contact passes");
assert.match(source, /function rebuildWorldObstacleGrid\(\)/, "fixed and gear obstacles are indexed in a collision grid");
assert.match(source, /gearSegmentsCache\.forEach/, "cached gear segments are reused during collision checks");
assert.match(source, /const FIXED_STEP = 1 \/ 120/, "the physics clock uses a fixed 120 Hz step");
assert.match(source, /function physicsSubstep\(dt\) \{\s*updateGears\(dt\)/, "gear movement advances in the fixed physics clock");
assert.match(source, /const substeps = Math\.min\(4, Math\.max\(1, Math\.ceil\(fastest \* dt \/ LINE_RADIUS\)\)\)/, "fast motion receives adaptive collision substeps");
assert.match(source, /MAX_STROKE_POINTS = 192/, "drawn lines have a bounded point count for mobile performance");
assert.match(source, /pixelRatioLimit = rect\.width < 600 \? 1\.5 : 2/, "mobile rendering uses an adaptive pixel ratio");
assert.match(source, /parStrokes: Math\.max\(1, strokesAllowed - 1\)/, "the third-star stroke threshold requires a better-than-maximum solution");
assert.match(source, /const rimSegments = 40/, "ring gears have physical rim collision segments");
assert.match(source, /unlocked === 12 && levels\.length > 12 && Number\(savedStars\[11\]\) > 0/, "legacy progress advances only after level 12 was cleared");

assert.ok(bundle.length > 400_000, "Three.js and the game are bundled locally");
assert.ok(html.includes("已解鎖 1 / 100"), "offline game shows the full level count");
const inlineStart = html.indexOf("<script>") + "<script>".length;
const inlineEnd = html.lastIndexOf("</script>");
const inlineScript = html.slice(inlineStart, inlineEnd).trimEnd();
const htmlShell = html.replace(inlineScript, "");
const escapedBundle = bundle.replace(/<\/script/gi, "<\\/script").trimEnd();
assert.equal((html.match(/<\/script/gi) ?? []).length, 1, "standalone HTML has exactly one real closing script tag");
assert.ok(inlineScript.startsWith(escapedBundle.slice(0, 200)), "standalone HTML embeds the current game bundle");
assert.ok(inlineScript.endsWith(escapedBundle.slice(-200)), "standalone HTML embeds the end of the current game bundle");
assert.ok(!htmlShell.includes('src="./game.bundle.js"') && !htmlShell.includes('href="./styles.css"'), "download is a single self-contained HTML file");
assert.ok((await stat(new URL("../dist/index.html", import.meta.url))).size > 400_000, "standalone HTML is present and non-empty");

console.log(JSON.stringify({ levels: 100, originalLevels: baseLevelCount, authoredExpansionBoards: authoredBoardCount, lateChapterSizes, chapters: chapters.map(chapter => ({ name: chapter.title, levels: chapter.levels.length })), goalTypes: [...goalTypes], standaloneHtmlBytes: (await stat(new URL("../dist/index.html", import.meta.url))).size }));
